---
services:
  xsearch:
    image: registry.xdata.si/xdata/xsearch:latest
    container_name: xsearch
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - xsearch-config:/etc/searxng:rw
      - xsearch-data:/var/lib/searxng:rw
    environment:
      - XSEARCH_BASE_URL=${XSEARCH_BASE_URL:-http://localhost:8080}
      - SEARXNG_SECRET=9e40f8a13ea31b6b717d37ef00426c42409f741655e782ce3a7ee8874b7f76f6
      - XSEARCH_BIND_ADDRESS=0.0.0.0
      - XSEARCH_IMAGE_PROXY=true
      - XSEARCH_LIMITER=false
      - XSEARCH_PUBLIC_INSTANCE=false
      - GRANIAN_WORKERS=${GRANIAN_WORKERS:-4}
      - GRANIAN_THREADS=${GRANIAN_THREADS:-4}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  xsearch-config:
  xsearch-data:
